services:
  - type: web
    name: mi-backend
    env: node
    buildCommand: "npm install"
    startCommand: "npm run start"
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://carconmar:carconmar26%40@projectefinal.cogmp.mongodb.net/projecteFINAL?retryWrites=true&w=majority
      - key: PORT
        value: "8080"